#-- Remove as Tabelas
DROP TABLE IF EXISTS ALOCACOES;
DROP TABLE IF EXISTS MATRICULAS;
DROP TABLE IF EXISTS ALUNOS;
DROP TABLE IF EXISTS TURMAS;
DROP TABLE IF EXISTS PROFESSORES;
DROP DATABASE sistema_academico_etec_heliopolis;