/* Mostrar tabelas feitas*/
SELECT * FROM ALUNOS;
SELECT Nome,Data_Nascimento FROM ALUNOS WHERE Nome_Mae = 'MARIA SILVA';
SELECT * FROM ALUNOS WHERE Nome Like '%SILVA%';

SELECT * FROM PROFESSORES;
SELECT NOME,CIDADE,BAIRRO FROM PROFESSORES WHERE ESTADO= 'SP';

SELECT * FROM TURMAS;
SELECT DESCRICAO, SERIE FROM TURMAS WHERE TURNO='N';

SELECT * FROM MATRICULAS;
SELECT MAT_ALUNO, VALOR FROM MATRICULAS WHERE COD_TURMA=3;

SELECT * FROM ALOCACOES;
SELECT COD_POSICAO FROM ALOCACOES WHERE CODIGO_PROFESSOR_ALOCA=1;

/* Mostrar Views Feitas*/
SELECT * FROM VW_LISTAALUNOS;
SELECT * FROM VW_LISTAALUNOS LIMIT 3;
SELECT * FROM VW_LISTAALUNOS2;

SELECT * FROM VW_LISTAPROFESSORES;
SELECT * FROM VW_LISTAPROFESSORES LIMIT 2;
SELECT * FROM VW_LISTAPROFESSORESNAODOADORES;

SELECT * FROM VW_LISTATURMAS;
SELECT * FROM VW_LISTATURMAS LIMIT 1;
SELECT * FROM VW_LISTATURMAS1SERIE;

SELECT * FROM VW_LISTAMATRICULAS;
SELECT * FROM VW_LISTAMATRICULAS LIMIT 2;
SELECT * FROM VW_LISTAMATRICULASBARATAS;

SELECT * FROM VW_LISTAALOCACOES;
SELECT * FROM VW_LISTAALOCACOES LIMIT 2;
SELECT * FROM VW_LISTAALOCACOESSEMTURMA1;