SELECT * FROM ALUNOS
GO
SELECT Nome,Data_Nascimento FROM ALUNOS WHERE Nome_Mae = 'MARIA SILVA' 
select * from alunos

SELECT *
FROM ALUNOS
WHERE Nome Like '%SILVA%'

SELECT * FROM VW_LISTAALUNOS;

SELECT * FROM VW_LISTAALUNOS LIMIT 3;

SELECT * FROM VW_LISTAALUNOS2;